-- =====================================================================
-- EcoEco · 03 · Dados iniciais
-- Conta oficial "Equipe EcoEco", comunidades, debates e biblioteca.
-- Também cria o primeiro código de convite. Rode depois do 02.
-- =====================================================================

-- Conta oficial (aparece como autora do conteúdo inicial)
insert into public.docs (collection, id, data, owner) values
('users', 'ecoeco', $j${"name":"Equipe EcoEco","username":"ecoeco","headline":"Conta oficial da EcoEco","bio":"Conteúdo inicial da plataforma: comunidades, debates e biblioteca.","role":"","school":"","city":"","link":"","education":"","experience":"","photo":"","cover":"","hue":2,"fake":false,"createdAt":1790000000000}$j$::jsonb, null)
on conflict (collection, id) do nothing;

-- Comunidades, debates e biblioteca
insert into public.docs (collection, id, data, owner) values
('communities', 'c_agro', $j${"author": "ecoeco", "createdAt": 1790100100000, "desc": "Safras, commodities, crédito rural e comércio exterior do agro.", "hue": 2, "icon": "AG", "name": "Agronegócio", "rules": "Traga a fonte dos números (Conab, IBGE, Cepea)."}$j$::jsonb, null),
('communities', 'c_estudantes', $j${"author": "ecoeco", "createdAt": 1790100400000, "desc": "Dúvidas de disciplinas, dicas de estudo, estágio e vida acadêmica.", "hue": 1, "icon": "EE", "name": "Estudantes de Economia", "rules": "Sem cola de prova. Ajude como gostaria de ser ajudado."}$j$::jsonb, null),
('communities', 'c_macro', $j${"author": "ecoeco", "createdAt": 1790100000000, "desc": "Política monetária e fiscal, inflação, câmbio e crescimento.", "hue": 0, "icon": "MA", "name": "Macroeconomia", "rules": "Cite dados e fontes; critique ideias, não pessoas."}$j$::jsonb, null),
('communities', 'c_mercado', $j${"author": "ecoeco", "createdAt": 1790100200000, "desc": "Renda fixa, ações, câmbio e carreira no mercado.", "hue": 5, "icon": "MF", "name": "Mercado financeiro", "rules": "Proibido recomendar compra ou venda de ativos."}$j$::jsonb, null),
('communities', 'c_publico', $j${"author": "ecoeco", "createdAt": 1790100300000, "desc": "Orçamento, gasto público, tributação e políticas públicas.", "hue": 3, "icon": "SP", "name": "Setor público", "rules": ""}$j$::jsonb, null),
('communities', 'c_trabalho', $j${"author": "ecoeco", "createdAt": 1790100500000, "desc": "Emprego, salários, informalidade e dados da PNAD Contínua.", "hue": 6, "icon": "ET", "name": "Economia do trabalho", "rules": ""}$j$::jsonb, null),
('debates', 'd_bitcoin', $j${"author": "ecoeco", "cat": "Mercado financeiro", "createdAt": 1787000000000, "desc": "Defensores comparam ao ouro digital; críticos apontam a volatilidade. O que define uma boa reserva de valor?", "sideA": "Sim, é", "sideB": "Não é", "title": "Bitcoin é reserva de valor?"}$j$::jsonb, null),
('debates', 'd_china', $j${"author": "ecoeco", "cat": "Economia internacional", "createdAt": 1790240000000, "desc": "Uma sondagem do Itaú com 34 setores mostrou a indústria cortando investimentos por causa dos juros e da concorrência chinesa. Ao mesmo tempo, a China é o maior comprador do agro e da mineração brasileiros.", "sideA": "Oportunidade", "sideB": "Ameaça", "title": "A China é mais oportunidade ou ameaça para a indústria brasileira?"}$j$::jsonb, null),
('debates', 'd_dados', $j${"author": "ecoeco", "cat": "Ensino e carreira", "createdAt": 1790260000000, "desc": "O mercado pede Python, SQL e estatística aplicada. Mas sem base teórica, o economista vira só um analista de dados. Qual deveria ser o equilíbrio na grade?", "sideA": "Sim, mais dados", "sideB": "Não, mais teoria", "title": "O curso de Economia deveria ter mais programação e ciência de dados?"}$j$::jsonb, null),
('debates', 'd_juros', $j${"author": "ecoeco", "cat": "Política monetária", "createdAt": 1790150000000, "desc": "Com a Selic em 13,75%, inflação de 4,22% em 12 meses e desemprego em 5,3%, o Banco Central deveria cortar mais rápido ou manter a cautela? #juros #copom", "sideA": "Remédio necessário", "sideB": "Freio excessivo", "title": "Juros altos: remédio necessário ou freio excessivo?"}$j$::jsonb, null),
('debates', 'd_minimo', $j${"author": "ecoeco", "cat": "Mercado de trabalho", "createdAt": 1786000000000, "desc": "A literatura empírica é dividida. No Brasil, o mínimo também corrige benefícios da Previdência, o que pesa nas contas públicas.", "sideA": "Sim, gera", "sideB": "Não, o efeito é pequeno", "title": "Aumento real do salário mínimo gera desemprego?"}$j$::jsonb, null),
('debates', 'd_petroleo', $j${"author": "ecoeco", "cat": "Política fiscal", "createdAt": 1790270000000, "desc": "A tensão entre EUA e Irã levou o barril de volta aos US$ 100. Segurar o preço ajuda a inflação no curto prazo, mas tem custo para a empresa e para o acionista, que inclui a União.", "sideA": "Sim, segurar", "sideB": "Não, repassar", "title": "Petróleo a US$ 100: a Petrobras deveria segurar o preço da gasolina?"}$j$::jsonb, null),
('library', 'l_bcb', $j${"author": "ecoeco", "authors": "Banco Central do Brasil", "createdAt": 1790100800000, "desc": "Atas do Copom, relatórios de política monetária e estudos. Leitura básica para acompanhar juros e inflação.", "kind": "Relatório", "link": "https://www.bcb.gov.br/publicacoes", "theme": "Macroeconomia", "title": "Publicações do Banco Central do Brasil", "year": ""}$j$::jsonb, null),
('library', 'l_blanchard', $j${"author": "ecoeco", "authors": "Olivier Blanchard", "createdAt": 1790100100000, "desc": "Referência para Macro I e II: IS-LM, curva de Phillips, expectativas e economia aberta. Ótimo para exercícios.", "kind": "Livro", "link": "", "theme": "Macroeconomia", "title": "Macroeconomia", "year": ""}$j$::jsonb, null),
('library', 'l_furtado', $j${"author": "ecoeco", "authors": "Celso Furtado", "createdAt": 1790100300000, "desc": "Leitura obrigatória para entender os ciclos da economia brasileira, do açúcar à industrialização.", "kind": "Livro", "link": "", "theme": "Economia brasileira", "title": "Formação Econômica do Brasil", "year": "1959"}$j$::jsonb, null),
('library', 'l_ipea', $j${"author": "ecoeco", "authors": "Instituto de Pesquisa Econômica Aplicada (Ipea)", "createdAt": 1790100900000, "desc": "Pesquisas aplicadas sobre políticas públicas, mercado de trabalho e desenvolvimento no Brasil, com acesso livre.", "kind": "Artigo", "link": "https://www.ipea.gov.br", "theme": "Economia brasileira", "title": "Textos para Discussão do Ipea", "year": ""}$j$::jsonb, null),
('library', 'l_kahneman', $j${"author": "ecoeco", "authors": "Daniel Kahneman", "createdAt": 1790100500000, "desc": "Porta de entrada para vieses e heurísticas. Leitura leve e muito útil para entender decisões reais.", "kind": "Livro", "link": "", "theme": "Economia comportamental", "title": "Rápido e Devagar: duas formas de pensar", "year": "2011"}$j$::jsonb, null),
('library', 'l_keynes', $j${"author": "ecoeco", "authors": "John Maynard Keynes", "createdAt": 1790100400000, "desc": "A obra que fundou a macroeconomia moderna. Denso, mas vale ler pelo menos os capítulos sobre demanda efetiva.", "kind": "Livro", "link": "", "theme": "Pensamento econômico", "title": "A Teoria Geral do Emprego, do Juro e da Moeda", "year": "1936"}$j$::jsonb, null),
('library', 'l_mankiw', $j${"author": "ecoeco", "authors": "N. Gregory Mankiw", "createdAt": 1790100000000, "desc": "Manual de introdução muito usado no primeiro ano. Explica oferta, demanda e os dez princípios da economia com exemplos do dia a dia.", "kind": "Livro", "link": "", "theme": "Introdução", "title": "Introdução à Economia", "year": ""}$j$::jsonb, null),
('library', 'l_piketty', $j${"author": "ecoeco", "authors": "Thomas Piketty", "createdAt": 1790100600000, "desc": "Estudo de longo prazo sobre desigualdade de renda e riqueza. Bom para debates sobre distribuição.", "kind": "Livro", "link": "", "theme": "Desenvolvimento", "title": "O Capital no Século XXI", "year": "2013"}$j$::jsonb, null),
('library', 'l_sidra', $j${"author": "ecoeco", "authors": "IBGE", "createdAt": 1790100700000, "desc": "Onde baixar séries oficiais do IBGE: IPCA, PNAD Contínua, PIB e muito mais. Essencial para trabalhos.", "kind": "Base de dados", "link": "https://sidra.ibge.gov.br", "theme": "Econometria e dados", "title": "SIDRA – Sistema IBGE de Recuperação Automática", "year": ""}$j$::jsonb, null),
('library', 'l_varian', $j${"author": "ecoeco", "authors": "Hal R. Varian", "createdAt": 1790100200000, "desc": "Clássico de micro intermediária: escolha do consumidor, firma, equilíbrio e teoria dos jogos.", "kind": "Livro", "link": "", "theme": "Microeconomia", "title": "Microeconomia: uma abordagem moderna", "year": ""}$j$::jsonb, null)
on conflict (collection, id) do nothing;

-- Código de convite do teste (troque se quiser). Até 40 contas.
insert into public.invites (code, max_uses) values ('ECOECO2026', 40)
on conflict (code) do nothing;
